---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


##Data Import: CSVs

Import data using `readr` pacakge


```{r}
library(readr)
litter_df = read_csv('data_import_examples/FAS_litters.csv')
litter_df = janitor::clean_names(litter_df)
```

Look at the data:

```{r}
litter_df
head(litter_df)
tail(litter_df)
```

```{r}
#View(litter_df)
```

```{r}
skimr::skim(litter_df)
```

`read_csv` options:

```{r}
read_csv('data_import_examples/FAS_litters.csv',na = c("","NA",999,88), skip= 2)
```

Other format:

```{r}
mlb_df = read_excel('data_import_examples/mlb11.xlsx')
```

```{r}
#View(mlb_df)
```

```{r}
lotr_word_df = read_excel('data_import_examples/mlb11.xlsx', range = "B3:B6")
```

Read SAS dataset:

```{r}
pulse_df = read_sas('data_import_examples/public_pulse_data.sas7bdat')
```

```{r}
#View(pulse_df)
```

##Data export

```{r}
write_csv(lotr_word_df, file = 'data_import_examples/lotr_word_df.csv')
```

##Why not base r?

```{r}
#dont_do_this = read.csv('data_import_examples/FAS_litters.csv')
```

